### ISSUE TITLE
design OOP for server part

### ISSUE THREAD

**Issue by Clu0D** [Clu0D/NewsSummarizerBot#3]
![Image](https://github.com/Clu08/NewsSummarizerBot/assets/153165874/a6d79a07-e1a3-4c2a-b3ae-a2cbe31b3ec3)

everyone assigned provides own idea of OOP design with an image

**Comment by Clu08** [comment]
![Image](https://github.com/Clu08/NewsSummarizerBot/assets/153165874/7321b14e-d001-42c3-906f-34ce30deb0ac)

suggestion of OOP design

**Comment by Deimoz** [comment]
![Image](https://github.com/Clu08/NewsSummarizerBot/assets/53293198/1b28555c-6a46-4bfc-a3a2-960c35ec86ce)
